
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8787/eureka
spring:
  application:
    name: MicroA
server:
  port: 8083